### PR TITLE
fix(firebase_images): Handle image not found in firebase and keep images when switch of order

### LINKED ISSUE #81: Fix bug of images ref when switch order in module

### PR DESCRIPTION
**Pull request by NyraSama**
# Description

What are changes related to ?
Fix finally the bug of deleted images when switching order of content in the modules
Doesn't make an error when the image is not found in firebase

# Tests

How has it been tested ?

- [X] Manually
- [ ] Automated tests
- [ ] QA
- [ ] Other

### CODE REVIEW

File: src/stores/data.ts [hunk 1]
```diff
@@ -419,27 +419,45 @@ export const useDataStore = defineStore("dataStore", {
         const modulePart = module.parts[+route.params.part];
         const modulePartElement = modulePart.elements[+route.params.elt];
         if (modulePartElement.file) {
```
Comment (LaurentMag) [inline src/stores/data.ts:421]: many if else if else, might think to split in different functions

Comment (LaurentMag) [inline src/stores/data.ts:421]: many if else if else, might think to split in different functions

**Review by LaurentMag — APPROVED** [review]
Approuved. 

But the loadImageUrl method in the data store have a LOT of  chained if else if else.
Could consider create differents functions to handle part of condition. Would make code more readable and maintainable
